name: Deploy to Live Channel

on:
  push:
    branches:
      - main
    # Optionally configure to run only for specific files. For example:
    # paths:
    # - "website/**"
permissions:
  checks: write
  contents: write

jobs:
  deploy_live_website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.1

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm ci --legacy-peer-deps
        working-directory: ./frontend

      - name: Build
        run: npm run build
        working-directory: ./frontend

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          projectId: your-Firebase-project-ID
          channelId: live
          entryPoint: ./frontend