name: Deploy to Preview Channel

on:
  pull_request:
    # Optionally configure to run only for specific files. For example:
    # paths:
    # - "website/**"
      branches:
        - main
     
permissions:
  checks: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.1

      - name: Install Node.js dependencies
        run: npm ci --legacy-peer-deps
        working-directory: ./frontend

      - name: Build
        run: npm run build
        working-directory: ./frontend
      
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_REACT_APP_BACKEND_URL: ${{ secrets.REACT_APP_BACKEND_URL }}
          envkey_REACT_APP_DISABLE_NAVBAR: ${{ secrets.REACT_APP_DISABLE_NAVBAR }}
          envkey_REACT_APP_APIKEY: ${{ secrets.REACT_APP_APIKEY }}
          envkey_REACT_APP_AUTHDOMAIN: ${{ secrets.REACT_APP_AUTHDOMAIN }}
          envkey_REACT_APP_PROJECTID: ${{ secrets.REACT_APP_PROJECTID }}
          envkey_REACT_APP_STORAGEBUCKET: ${{ secrets.REACT_APP_STORAGEBUCKET }}
          envkey_REACT_APP_MESSAGINGSENDERID: ${{ secrets.REACT_APP_MESSAGINGSENDERID }}
          envkey_REACT_APP_APPID: ${{ secrets.REACT_APP_APPID }}
          envkey_REACT_APP_MEASUREMENTID: ${{ secrets.REACT_APP_MEASUREMENTID }}
          directory: ./frontend
          filename: .env

      - uses: FirebaseExtended/action-hosting-deploy@v0
        id: firebase-preview
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
          expires: 30d
          projectId: code-critters-b5d86
          entryPoint: ./frontend
             